# file ./cheatsheets/.github/workflows/deploy.yml

name: 'ci'

on:
  push:
    branches:
      - master
      - mkdocs

env:
  ebook_name: 'cheatsheets'

jobs:
  deploy_docs:
    name: 'deploy docs'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: 'Configure git'
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    - name: 'Install mkdocs venv'
      run: make venv
    - name: 'Build mkdocs'
      run: make gh-deploy
